## Exercises: Modify the dataset

In [74]:
import pandas as pd
employees = pd.read_json("../Data/employees.json")

**Current state of the "employees" dataset**

Rerun the code block below after each modification you do, to see its current state.

In [85]:
employees

Name                            Email              Job Title  \
0          John Doe         john.doe@mockcompany.com         Sales Director   
1        Jane Smith       jane.smith@mockcompany.com         HR Coordinator   
2   Michael Johnson  michael.johnson@mockcompany.com      Software Engineer   
3    Sarah Williams   sarah.williams@mockcompany.com   Marketing Specialist   
4       David Brown      david.brown@mockcompany.com             HR Manager   
5       Emily Davis      emily.davis@mockcompany.com  IT Support Specialist   
6      Jacob Wilson     jacob.wilson@mockcompany.com   Sales Representative   
7      Olivia Moore     olivia.moore@mockcompany.com      Marketing Manager   
8         Ethan Lee        ethan.lee@mockcompany.com      Financial Analyst   
9     Sophia Taylor    sophia.taylor@mockcompany.com           HR Assistant   
10  Daniel Claesson  daniel.claesson@mockcompany.com            SW Engineer   
11  Daniel Claesson  daniel.claesson@mockcompany.com            SW Engineer   

      Salary       Department  
0   132000.0            Sales  
1    60000.0  Human Resources  
2   110000.0               IT  
3    82500.0            Sales  
4    90000.0  Human Resources  
5    55000.0               IT  
6    88000.0            Sales  
7   110000.0            Sales  
8    93500.0            Sales  
9    50000.0  Human Resources  
10  100000.0               IT  
11  100000.0               IT

**Do the following operations on the "employees" dataset:**

**OP1:** Create a new column "name" which contains the full name (eg. "John Doe") for each employee.

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>name</b><br>
&nbsp;&nbsp;&nbsp;John Doe<br>
&nbsp;&nbsp;&nbsp;Jane Smith<br>
&nbsp;&nbsp;&nbsp;Michael Johnson<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [76]:
employees['name'] = employees['first_name'] + " " + employees['last_name']

<div style="display: inline">
<b>OP2:</b> Create a new column "email" with the following format: firstname.lastname@mockcompany.com
</div><br>

*Note: email addresses should be all lower case.*

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>email</b><br>
&nbsp;&nbsp;&nbsp;john.doe@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;jane.smith@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;michael.johnson@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [77]:
employees['email'] = employees['first_name'].str.lower() + "." + employees['last_name'].str.lower() + "@mockcompany.com"

**OP3:** Remove the columns "first_name" and "last_name", and put the columns "name" and "email" first.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>name&nbsp;&nbsp;&nbsp;email&nbsp;&nbsp;&nbsp;job_title&nbsp;&nbsp;&nbsp;salary&nbsp;&nbsp;&nbsp;department</b>
</details>

In [78]:
# delete två kolumner:
employees.drop(columns=['first_name','last_name'], inplace=True)

In [79]:
# flyttar om kolumnerna genom att skapa en ny DataFrame med samma namn:
#employees.columns = ['job_title','salary','department','name','email'] # fel sätt, denna byter bara namn på kolumnerna
employees = employees.reindex(columns=['name','email','job_title','salary','department'])


**OP4:** Update column titles to make the first letter in each title upper case. Also replace the underscore character in "job_title" with a space.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>Name&nbsp;&nbsp;&nbsp;Email&nbsp;&nbsp;&nbsp;Job title&nbsp;&nbsp;&nbsp;Salary&nbsp;&nbsp;&nbsp;Department</b>
</details>

In [80]:
my_new_cols = []

for item in employees.columns:
    if "_" in item:
        item = item.replace("_"," ")
    my_new_cols.append(item.title())

employees.columns = my_new_cols

**OP5:** Change the data type of column "Salary" to float64.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;Salary: int64 => float64
</details>

In [81]:
employees.astype({'Salary':'float64'})

Name                            Email              Job Title  \
0         John Doe         john.doe@mockcompany.com         Sales Director   
1       Jane Smith       jane.smith@mockcompany.com         HR Coordinator   
2  Michael Johnson  michael.johnson@mockcompany.com      Software Engineer   
3   Sarah Williams   sarah.williams@mockcompany.com   Marketing Specialist   
4      David Brown      david.brown@mockcompany.com             HR Manager   
5      Emily Davis      emily.davis@mockcompany.com  IT Support Specialist   
6     Jacob Wilson     jacob.wilson@mockcompany.com   Sales Representative   
7     Olivia Moore     olivia.moore@mockcompany.com      Marketing Manager   
8        Ethan Lee        ethan.lee@mockcompany.com      Financial Analyst   
9    Sophia Taylor    sophia.taylor@mockcompany.com           HR Assistant   

     Salary       Department  
0  120000.0            Sales  
1   60000.0  Human Resources  
2  110000.0               IT  
3   75000.0            Sales  
4   90000.0  Human Resources  
5   55000.0               IT  
6   80000.0            Sales  
7  100000.0            Sales  
8   85000.0            Sales  
9   50000.0  Human Resources

**OP6:** The company decided to give everyone in sales a 10% salary increase. Update the dataset accordingly.

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;John Doe&nbsp;&nbsp;&nbsp;132000.0<br>
&nbsp;&nbsp;&nbsp;Jane Smith&nbsp;&nbsp;&nbsp;60000.0<br>
&nbsp;&nbsp;&nbsp;Michael Johnson&nbsp;&nbsp;&nbsp;110000.0	<br>
&nbsp;&nbsp;&nbsp;Sarah Williams&nbsp;&nbsp;&nbsp;82500.0<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [82]:
for item in range(len(employees['Job Title'])):
    if "Sales" in employees['Department'][item]:
        employees['Salary'][item] = employees['Salary'][item] * 1.1

C:\Users\danie\AppData\Local\Temp\ipykernel_25680\319769254.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees['Salary'][item] = employees['Salary'][item] * 1.1
C:\Users\danie\AppData\Local\Temp\ipykernel_25680\319769254.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees['Salary'][item] = employees['Salary'][item] * 1.1
C:\Users\danie\AppData\Local\Temp\ipykernel_25680\319769254.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view

**OP7:** The company hired a new software engineer. Add a new row with appropriate values to the dataset.
<details>
<summary>Result</summary>
<br>
<b>Example:</b><br>
&nbsp;&nbsp;&nbsp;<b>Name:</b> Jennifer Lee<br>
&nbsp;&nbsp;&nbsp;<b>Email:</b> jennifer.lee@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;<b>Job title:</b> Software Engineer<br>
&nbsp;&nbsp;&nbsp;<b>Salary:</b> 100.000<br>
&nbsp;&nbsp;&nbsp;<b>Department:</b> IT<br>
</details>

In [84]:
# new_empl = {'Name':['Daniel Claesson'],'Email':['daniel.claesson@mockcompany.com'],'Job Title':['SW Engineer'],'Salary':[100000],'Department':['IT']}
# new_empl_df = pd.DataFrame(new_empl)

# employees.loc[10] = new_empl_df
new_idx = employees.index.max()+1
employees.loc[new_idx] = ['Daniel Claesson','daniel.claesson@mockcompany.com','SW Engineer',100_000,'IT']

**OP8:** The company decided to hire a lot of new software engineers.

Create python code that asks the user to input the name and salary of the new software engineer, and then automatically adds the new employee to the dataset. Also, ensure that each employee get a unique index in the dataset.

<details>
<summary>Result</summary>
<br>
<b>Example:</b><br>
&nbsp;&nbsp;&nbsp;Input name of new software engineer: Daniel Brown<br>
&nbsp;&nbsp;&nbsp;Input the salary for Daniel Brown: 95.000<br>
<br>
&nbsp;&nbsp;&nbsp;<b>Name:</b> Daniel Brown<br>
&nbsp;&nbsp;&nbsp;<b>Email:</b> daniel.brown@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;<b>Job title:</b> Software Engineer<br>
&nbsp;&nbsp;&nbsp;<b>Salary:</b> 95.000<br>
&nbsp;&nbsp;&nbsp;<b>Department:</b> IT<br>
</details>

In [94]:
first_name = input('Input first name: ')
last_name = input('input last name: ')
salary = float(input('Input salary'))

new_idx = employees.index.max()+1

employees.loc[new_idx] = [first_name + " " + last_name,first_name.lower()+"."+last_name.lower()+"@mockcompany.com",'SW Engineer', salary, 'IT']
employees


Name                             Email              Job Title  \
0           John Doe          john.doe@mockcompany.com         Sales Director   
1         Jane Smith        jane.smith@mockcompany.com         HR Coordinator   
2    Michael Johnson   michael.johnson@mockcompany.com      Software Engineer   
3     Sarah Williams    sarah.williams@mockcompany.com   Marketing Specialist   
4        David Brown       david.brown@mockcompany.com             HR Manager   
5        Emily Davis       emily.davis@mockcompany.com  IT Support Specialist   
6       Jacob Wilson      jacob.wilson@mockcompany.com   Sales Representative   
8          Ethan Lee         ethan.lee@mockcompany.com      Financial Analyst   
9      Sophia Taylor     sophia.taylor@mockcompany.com           HR Assistant   
11   Daniel Claesson   daniel.claesson@mockcompany.com            SW Engineer   
12  Pelle Pettersson  pelle.pettersson@mockcompany.com            SW Engineer   
13     Henrik Moberg     henrik.moberg@mockcompany.com            SW Engineer   
14   Julia Andersson   julia.andersson@mockcompany.com            SW Engineer   
15   Rutger Adamsson   rutger.adamsson@mockcompany.com            SW Engineer   
16  Gunilla Svensson  gunilla.svensson@mockcompany.com            SW Engineer   

      Salary       Department  
0   132000.0            Sales  
1    60000.0  Human Resources  
2   110000.0               IT  
3    82500.0            Sales  
4    90000.0  Human Resources  
5    55000.0               IT  
6    88000.0            Sales  
8    93500.0            Sales  
9    50000.0  Human Resources  
11  100000.0               IT  
12   88000.0               IT  
13   77000.0               IT  
14  200000.0               IT  
15   34000.0               IT  
16  101000.0               IT

**OP9:** Olivia Moore quits her job. Remove her data from the dataset.

In [93]:
employees.drop(index=7, inplace=True)


**OP10**: Make sure that the python script in *OP8* still gives a unique index to each new employee, even after removing rows.

### Final note:
Just to be clear, a real company would most likely store their employee data in a database, and loading them into a pandas dataframe to do these kind of operations wouldn't make much sense. The above examples are purely for learning the different operations of pandas.